services:
  # livekit:
  #   image: livekit/livekit-server:latest
  #   command: >
  #     --dev
  #     --node-ip 0.0.0.0
  #     --bind 0.0.0.0
  #   ports:
  #     - "7880:7880"   
  #     - "7881:7881"   
  #   environment:
  #     LIVEKIT_API_KEY: devkey
  #     LIVEKIT_API_SECRET: secret

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: livekitdb
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
