
### Get Token
GET http://localhost:3000/livekit/token?roomName=quickstart-room&userName=quickstart-user

### Dispatch Agent
POST http://localhost:3000/livekit/session
Content-Type: application/json

{
  "userName": "quickstart-user"
}

